##H2 Database Connection Properties
spring:
    datasource:
        url: jdbc:h2:mem:testdb
        #url: jdbc:h2:file:./h2-database
        driver-class-name: org.h2.Driver
        username: sa
        password: ''

    h2:
      console:
          enabled: true
          path: /h2-console
          settings:
              trace:
                  web-allow-others: false

    #validate | update | create | create-drop
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        defer-datasource-initialization: true
        properties:
            hibernate:
                format_sql=true:

    flyway: enabled=false
